### ISSUE TITLE
Menu doesn't seem to work ...

### ISSUE THREAD

**Issue by KurtHofman** [intersystems-ru/cache-tort-git#17]
I installed and configured the cache-tort-git.
I followed the steps :
1. Select menu Tortoise Git Settings and set up options for Git (e.g. Proxy). This options are stored in folder that you chose as temp.
2. Chose menu Create Repo. Press OK. One more time. -> Repo is created under C:\InterSystems\Cache\bin\SAMPLES
3. Now menu has full view. -> doesn't show
4. A new menu item appears in context menu — "Git -> Add to Source Control".-> doesn't show
I only get Settings,TortoiseGit Settings, ...

**Comment by adaptun** [comment]
Hi Kurt.
Please try to restart Studio.
If this does not help, please provide $zv and output of following command:
zw ^|"%SYS"|Git

**Comment by adaptun** [comment]
Kurt, If after restart you see full menu, then I think I've just fixed this error that caused restart require.

**Comment by KurtHofman** [comment]
^|"%SYS"|Git("%defaultTemp")="c:\temp\"
^|"%SYS"|Git("%gitBinPath")="""C:\Program Files\TortoiseGit\bin\TortoiseGitProc.exe"""

Cache for Windows (x86-64) 2015.1 (Build 425U) Mon Jan 19 2015 19:18:38 EST

**Comment by adaptun** [comment]
So Studio restart did not help?

**Comment by KurtHofman** [comment]
Nope

**Comment by adaptun** [comment]
Please also provide output of following commands (in the namespace where source-control plugin is enabled):
USER>w ##class(%SourceControl.Git.Utils).IsNamespaceInGit()
1
USER>w ##class(%SourceControl.Git.Utils).TempFolder()
c:\work\tgit\
USER>w ##class(%SourceControl.Git.Utils).GitBinExists()
1
USER>w ##class(%File).Exists(##class(%SourceControl.Git.Utils).TempFolder()_".git")
1
USER>zw ^Git

**Comment by adaptun** [comment]
And output of following command:
USER>write ##class(%SourceControl.Git.Utils).TempFolder()_".git"
c:\work\tgit\.git

**Comment by KurtHofman** [comment]
SAMPLES>w ##class(%SourceControl.Git.Utils).IsNamespaceInGit()
0
SAMPLES>w ##class(%SourceControl.Git.Utils).TempFolder()
SAMPLES\
SAMPLES>w ##class(%SourceControl.Git.Utils).GitBinExists()
1
SAMPLES>w ##class(%File).Exists(##class(%SourceControl.Git.Utils).TempFolder()_".git")
0

SAMPLES>zw ^Git
^Git("settings","namespaceTemp")="SAMPLES\"
 
SAMPLES>write ##class(%SourceControl.Git.Utils).TempFolder()_".git"
SAMPLES\.git
SAMPLES>

**Comment by adaptun** [comment]
Please go to Git -> Settings menu and specify full path in "Temp folder for this namespace".

For example, "c:\temp\SAMPLES". You'll need to create repo again.

Also, please delete (or move to the new path) folder C:\InterSystems\Cache\bin\SAMPLES

**Comment by KurtHofman** [comment]
Superb, now it works, thanks very much for the quick support

**Comment by adaptun** [comment]
You are welcome. Thanks for reporting this. 
I hope I've fixed it and now default path will be absolute not relative.
