### ISSUE TITLE
Export on workstation in stead of on server ...

### ISSUE THREAD

**Issue by KurtHofman** [intersystems-ru/cache-tort-git#18]
We have a central Caché-server to wich the developers connect with Caché-studio.
I can configure Cache-tort-git in the local Caché Studio's but the exports are saved on the server instead of on the workstations.
Is it possible that cache-tort-git exports directly in the right folder on the workstations ?

**Comment by adaptun** [comment]
No, Kurt, there is no way to do this. You need to have Caché server and Studio both on local machine
