### ISSUE TITLE
Import exclusions

### ISSUE THREAD

**Issue by tsafin** [intersystems-ru/cache-tort-git#19]
Until recently I had non-importable items in the repository, so "Import All" if failed on loading, but ddin't bring anything undesired.

But right now I want to put a few actual Studio projects as examples of containers, and I do not want to get them imported by "Import All" (but rather they will be used/loaded/unloaded as part of unit-testing scenarios). Like here https://github.com/intersystems-ru/CPM/tree/package_xml/t/simple/simple.xml

Could you please provide exclude patterns functionality?

**Comment by adaptun** [comment]
starting with ef61d4c921a87ece98a8f4a15a81dcca2d89cc74 cache-tort-git only imports items that are tracked by source-control
