### ISSUE TITLE
I can not save a new file in a .csp already versioned folder

### ISSUE THREAD

**Issue by lucasscarduelli** [intersystems-ru/cache-tort-git#22]
After I add a folder with CSP pages to version control I can not create any more .csp file in it.

After creating the new file I try to save him and the error message as the image below.

![bug](https://cloud.githubusercontent.com/assets/6307081/6687149/af1e6a7a-cc86-11e4-963a-272967b39ae4.png)

My workstation is in pt-BR, so the translation of the message is: "ERROR #5012: The file 'c:\temp\TESTE_VERSIONAMENTO\csp\teste\Untitled4.csp.xml' not exists"

**Comment by lucasscarduelli** [comment]
Pull request #23

**Comment by adaptun** [comment]
Can you please provide output of 
zwrite ^Git from namespace where error happens

**Comment by lucasscarduelli** [comment]
This file really not exists, the problem is the "OnBeforeLoad" from %SourceControl.Git is executed before creating the file also.

**Comment by adaptun** [comment]
I don't think that this is the problem OnBeforeLoad should not throw error if there are no external file.

**Comment by lucasscarduelli** [comment]
Yes, i agree. The problem happens when the " LoadIfOutdated " method tries to load the file and it does not exist. I think we can fix this by validating method if the file actually exists.

**Comment by lucasscarduelli** [comment]
Ok, it's resolved but my last commit resolved a potencial bug too. 
You can merge?

**Comment by adaptun** [comment]
I think we don't need to check that file exists in LoadIfOutdated because IsRoutineOutdated should return false if there is no corresponding file on disk, so there is no need to merge.

**Comment by lucasscarduelli** [comment]
In my opinion the most correct is to validate if the file or routine exists and don't set a fictious date to this. 
So for me the responsibilities of validations are confused , if we think of quality as correct code would be to separate these validations .
