### ISSUE TITLE
CSP folder don't import if it does not exist in local directory

### ISSUE THREAD

**Issue by lucasscarduelli** [intersystems-ru/cache-tort-git#32]
I have a versioned CSP folder on my CSP application , when I create a new local environment where that folder does not exist yet in the CSP application, the version control it does not create or import any of your files or subfolders.

**Comment by lucasscarduelli** [comment]
News?

**Comment by adaptun** [comment]
Please provide steps to reproduce.

**Comment by lucasscarduelli** [comment]
You should have two equal development environments , in one of them you should create a new csp page in a new folder and commit this change.

When you integrate this new amendment to the second development environment will see the new folder structure and also the new file will not be imported.

**Comment by adaptun** [comment]
I cannot reproduce this.

I've tried following on Cache' 2015.2:
--------------
0. In USER namespace I set Git -> Settings -> "Temp folder for this namespace" to c:\temp\test 
1. I've created empty repository in USER.
2. Created csp file test.csp and placed it in /csp/user/test1/test.csp
3. Added that file to Git (right-click: Git -> Add To Source Control)
4. I've called Git -> Commit, added /csp/test1/test.csp.xml, and commited it.
5. I've switched to SAMPLES namespace.
6. Git -> Settings -> "Temp folder for this namespace" points to the same folder as in USER namespace
7. Git -> Import All.
8. Now, file /csp/samples/test1/test.csp is created as well as folder /csp/samples/test1
--------------

Please check if those steps work for you. If yes -- what is the difference with what you do?
If those steps do not work for you too, i.e. in 8) you don't see file and/or folder created, then we might look at what point it fails.

FWIW, I do not create any directories on import.
I only call $system.OBJ.Load(filename,"-l-d") in %SourceControl.Git.Utils:LoadIfOutdated method.

**Comment by adaptun** [comment]
@lucasscarduelli Can you please provide steps to reproduce as in previous comment or check if these steps work for you. Thanks!

**Comment by adaptun** [comment]
no response -- closing
