### ISSUE TITLE
Project hooks

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/cache-tort-git#33]
Here's an idea: hooks for projects. I got 3 implementations:

- On ExportItem we check `^Git("hook") = class, method` and execute `do $classmame(class, method)` or  `do $classmame(class, method, itemname)`
- Same as previous but only once after user presses `Commit` button
- We check for each class: does method  `OnExport` exist? If yes, do something.

Ideas? 
I require it for MDX2JSON (need to execute 1 action before commit), but I want my changes integrated into master branch so let's work out a solution for everybody.

**Comment by eduard93** [comment]
So I'm all for second one, I guess.

**Comment by eduard93** [comment]
%SourceControl.Git.Utils:UserAction -> elseif ..IsMenuGitCommand(menuItemName)

**Comment by adaptun** [comment]
Hooks to hooks. Fruitful idea.

What do you need to do before commit?

Can you do this with Tortoise Git Hook Scripts?

**Comment by eduard93** [comment]
> What do you need to do before commit?

I want to set  last successful commit as parameter in one class and this class. Too many versions floating around and I want to identify it immediately and not by studying code

> Can you do this with Tortoise Git Hook Scripts?

Actually, probably yeas, but it's really internal Cache operation
