### ISSUE TITLE
Handle $$$ClassDoesNotExist error when deleting classes

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/cache-tort-git#40]
I often receive this error:
```
Class delete mvk.production.ContractPreparationProcess
Error #5351: Class 'package.classname' Does not exist.
Error: could not delete  'package.classname.cls'
```

This error should not be displayed, but rather `^Git` global should be automatically actualized by removing offending class entry.

**Comment by adaptun** [comment]
I don't know how to reproduce this.
I've added some check
