### ISSUE TITLE
What is procedure for updating plugin to different version?

### ISSUE THREAD

**Issue by aedahh** [intersystems-ru/cache-tort-git#42]
Hello,

What is procedure for updating plugin to a newer release?
My installation already have plugin installed and setup for my namespace.
Currently using: "cache-tort-git" LastModified="2015-02-24 12:30:27.321554"
Want to update to "cache-tort-git" LastModified="2016-07-31 23:57:25.117897"

Thanks

**Comment by eduard93** [comment]
Just download and import new  code.
