### ISSUE TITLE
Force Exprort All, ERROR #6304: Unable to export item

### ISSUE THREAD

**Issue by aedahh** [intersystems-ru/cache-tort-git#44]
Hello,
When do Force Exprort All from Git menu in Cahce Studio, I am getting error, "ERROR #6304: Unable to export item 'myclass.something' because XML export does not support items of this type. Will skip this item."

However, the same class, exports fine from Studio.
Workspace > Project tab > select myclass.something > right-click Export.

What is this error and how can I resolve it or how can I debug to see what line inside that class is causing Force Export All issue?

Thx!

**Comment by adaptun** [comment]
@aedahh . Do you still have this error, if yes, please attach output of command:

zwrite ^Git

**Comment by adaptun** [comment]
no response, closing
