### ISSUE TITLE
Git Plugin only allows to add 10 routines at a time

### ISSUE THREAD

**Issue by perlaEscReady** [intersystems-ru/cache-tort-git#46]
Currently the Git plugin only allows us to submit 10 routines to the repository at a time using the UI, is there a workaround that can be used so that more routines can be submitted at once? If not, this should be added, the capability to submit a folder of routines instead of selecting a small group.

**Comment by adaptun** [comment]
Please provide more detailed description with screenshots.

In other words, steps, to reproduce the problem.

Thank you!

**Comment by DanielAguilarGarcia** [comment]
Hi adaptun, we have the same problem with the contextual menu, when we want add routines to the SourceControl

Screenshot when we select few routines:

![ok](https://cloud.githubusercontent.com/assets/28974107/26498955/2382cc90-4231-11e7-9573-2bdb0b751ab8.png)


Screenshot when we select many routines:

![error](https://cloud.githubusercontent.com/assets/28974107/26498976/35decc4a-4231-11e7-8656-419a1ead6294.png)


SubMenu "add to source control" doesn't appear.

Thanks!

**Comment by adaptun** [comment]
@perlaEscReady  @DanielAguilarGarcia  please check again with latest version. This should be fixed.

**Comment by DanielAguilarGarcia** [comment]
Thanks @adaptun  now works perfectly!!
