### ISSUE TITLE
Error adding Routines to control manager

### ISSUE THREAD

**Issue by DanielAguilarGarcia** [intersystems-ru/cache-tort-git#47]
Hello, when select many routines at a same time and click on Add to SourceControl we have this error:

![image](https://user-images.githubusercontent.com/28974107/29456374-a9e133e6-8415-11e7-9f7a-f0847b785ec9.png)

 class '%Studio.SourceControl.Interface', method 'UserAction': SUBSCRIPT 201 zTS+22^%Library.RoutineMgr.1 ^oddDEF("")

class '%Studio.SourceControl.Interface', method 'GetStatus': SUBSCRIPT 201 zTS+22^%Library.RoutineMgr.1 ^oddDEF("")

Thanks!

**Comment by adaptun** [comment]
@DanielAguilarGarcia I'll look into this, but why are you adding classes to Source control one-by-one? Just right-click on package and add whole package!

**Comment by patrickrioux** [comment]
This is for routines

**Comment by adaptun** [comment]
This is not a problem with cache-tort-git; the same problem with the empty source control class

**Comment by DanielAguilarGarcia** [comment]
Ok, Thank you!
