### ISSUE TITLE
Can't get it up

### ISSUE THREAD

**Issue by SaturnCorp** [intersystems-ru/cache-tort-git#50]
Trying to import xml's and get the error: 

_"ERROR #6301 Line: 3 Offset: 34 ERROR #5883: Item '%SourceControl.Git' is mapped from a database that you do not have write permission on. Will skip this item."_

I'm running on Windows 10 server with full privileges in Cache and in Windows. Export and Import of other cls files (not part of this pull) work fine. Any suggestions?

**Comment by eduard93** [comment]
Check readme, section `Installation in Caché`, step 1: Enable write-access to CACHELIB database via the Management Portal. (This is required for csp-page with settings import.)

**Comment by SaturnCorp** [comment]
Thanks for the input, but I think I've got this set up already.  See attached screen shots. Is there any other place except  System > Security Management > Resources where this needs to take place?
![resource security settings](https://user-images.githubusercontent.com/43504359/47297798-c4bbdb80-d5db-11e8-9b71-774c4d685bd3.jpg)

![terminal import errors](https://user-images.githubusercontent.com/43504359/47297807-cab1bc80-d5db-11e8-99cd-b2e876d27420.jpg)

**Comment by adaptun** [comment]
@SaturnCorp .

Yes, you should enable RW-access to CACHELIB in Management Portal -> System Administration -> Configuration -> System Configuration -> Local Databases -> CACHELIB.

Clear checkbox near "Mount Read-Only"

**Comment by SaturnCorp** [comment]
That worked.  Thanks very much
